### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by ssoonmi** [lhsteele/Organa#3]
Really nice Sample State!

### projects
- [x] should be able to have multiple `teamIds`

### ui: teamModal
- [x] should be a boolean, not a React component

### lists
- [x] need to update schema to reflect the lists changes

**Comment by ssoonmi** [comment]
Just added another bullet point

**Comment by lhsteele** [comment]
The schema is update, but I will update Sample State to reflect the lists addition.

**Comment by ssoonmi** [comment]
`listId` for a `task` doesn't need to be an array

**Comment by lhsteele** [comment]
Thanks! I've updated the schema.
